version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: allauser          # Username for PostgreSQL
      POSTGRES_PASSWORD: allapassword  # Password for PostgreSQL user
      POSTGRES_DB: alladb              # Default database
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent data storage
      - ./development/pg_hba.conf:/etc/postgresql/postgresql.conf.d/pg_hba.conf  # Custom pg_hba.conf file
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Default login email for PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin           # Default login password for PGAdmin
      PGADMIN_SERVER_MODE: "False"  # Disable server mode to allow default login
      PGADMIN_SERVER_NAME: "AllPostgreSQL"  # Name of the PostgreSQL server in PGAdmin
      PGADMIN_SERVER_HOST: "postgres"  # Host name of the PostgreSQL service (from docker-compose)
      PGADMIN_SERVER_PORT: 5432  # Port for PostgreSQL
      PGADMIN_SERVER_USER: "allauser"  # PostgreSQL username
      PGADMIN_SERVER_PASSWORD: "allapassword"  # PostgreSQL password
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Persistent storage for PGAdmin data (including server connections)
    ports:
      - "5054:80"  # Expose PGAdmin UI on port 5054
    networks:
      - mynetwork
    depends_on:
      - postgres  # Ensure PostgreSQL is up before PGAdmin starts

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local  # Create a persistent volume for PostgreSQL data
  pgadmin-data:
    driver: local  # Persistent volume to store PGAdmin data
